name: Push to Replicate

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Cog
        run: |
          curl -s https://raw.githubusercontent.com/replicate/cog/main/scripts/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Log in to Replicate
        run: |
          ~/.local/bin/cog login --token ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Push model to Replicate
        run: |
          ~/.local/bin/cog push r8.im/nanayka/nanayka-my-model
